name: Deploy Images to GHCR when pushing to main branch

on:
  push:
    branches:
      - main

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      current_version: ${{ steps.get_version.outputs.current_version }}

    steps:
      - name: Get current version
        id: get_version
        run: |
          CURRENT_VERSION_JSON=`curl -s https://plexamp.plex.tv/headless/version.json`
          CURRENT_VERSION=`echo $CURRENT_VERSION_JSON | jq -r .latestVersion`
          echo "::set-output name=current_version::$CURRENT_VERSION"

  build-amd64:
    needs: get-version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build AMD64 image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 -t ghcr.io/${{github.actor}}/plexamp:amd64 --push .
          docker buildx build --platform linux/amd64 -t ghcr.io/${{github.actor}}/plexamp:amd64-${{ needs.get-version.outputs.current_version }} --push .

  build-arm64:
    needs: get-version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build ARM64 image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/arm64 -t ghcr.io/${{github.actor}}/plexamp:arm64v8 --push .
          docker buildx build --platform linux/arm64 -t ghcr.io/${{github.actor}}/plexamp:arm64v8-${{ needs.get-version.outputs.current_version }} --push .

  build-arm32:
    needs: get-version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build ARM32v7 image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/arm/v7 -f Dockerfile.arm32v7 -t ghcr.io/${{github.actor}}/plexamp:arm32v7 --push .
          docker buildx build --platform linux/arm/v7 -f Dockerfile.arm32v7 -t ghcr.io/${{github.actor}}/plexamp:arm32v7-${{ needs.get-version.outputs.current_version }} --push .

  create-manifests:
    needs: [get-version, build-amd64, build-arm64, build-arm32]
    runs-on: ubuntu-latest

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Create multi-arch manifests
        run: |
          docker buildx imagetools create -t ghcr.io/${{github.actor}}/plexamp:latest \
            ghcr.io/${{github.actor}}/plexamp:amd64 \
            ghcr.io/${{github.actor}}/plexamp:arm64v8 \
            ghcr.io/${{github.actor}}/plexamp:arm32v7
          docker buildx imagetools create -t ghcr.io/${{github.actor}}/plexamp:${{ needs.get-version.outputs.current_version }} \
            ghcr.io/${{github.actor}}/plexamp:amd64-${{ needs.get-version.outputs.current_version }} \
            ghcr.io/${{github.actor}}/plexamp:arm64v8-${{ needs.get-version.outputs.current_version }} \
            ghcr.io/${{github.actor}}/plexamp:arm32v7-${{ needs.get-version.outputs.current_version }}